name: Code Analysis
on: [push]
jobs:

  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: list
        uses: kitconcept/code-analysis-action@main
        with:
          check: 'ls'
          path: '/github'

      - name: Check
        uses: kitconcept/code-analysis-action@main
        with:
          check: 'black'
          path: |
            src
            setup.py
