name: Code Analysis
on: [push]
jobs:

  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Run check
        uses: kitconcept/code-analysis-action@main
        with:
          check: 'black'
          path: |
            src
            setup.py

  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Run check
        uses: kitconcept/code-analysis-action@main
        with:
          check: 'flake8'
          path: |
            src
            setup.py

  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Run check
        uses: kitconcept/code-analysis-action@main
        with:
          check: 'isort'
          path: |
            src
            setup.py

  pyroma:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Run check
        uses: kitconcept/code-analysis-action@main
        with:
          check: 'pyroma'
          path: .

  zpretty:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Run check
        uses: kitconcept/code-analysis-action@main
        with:
          check: 'zpretty'
          path: src
